github.com:
    users:
        Web-Dev-Codi:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: Web-Dev-Codi
